# Generated by Django 4.2 on 2025-12-07 16:11

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MatchDeportivoAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('deporte', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('lugar', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('fecha', models.DateField(default=datetime.date.today)),
                ('hora_inicio', models.TimeField(default=datetime.time(18, 0))),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('nivel', models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20)),
                ('cupos', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('organizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(blank=True, related_name='actividades_participando', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='log',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('nickname', models.CharField(blank=True, max_length=50)),
                ('icono_perfil', models.CharField(blank=True, max_length=50, null=True)),
                ('disciplina_preferida', models.CharField(blank=True, max_length=50, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=255, null=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nivel', models.CharField(blank=True, max_length=20, null=True)),
                ('horarios', models.CharField(blank=True, max_length=200, null=True)),
                ('radio', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_ACTIVIDAD', 'Nueva Actividad Cercana'), ('CONFIRMACION_UNION', 'Confirmación de Unión'), ('NUEVA_CALIFICACION', 'Nueva Calificación')], max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MatchDeportivoAPP.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
