# Generated by Django 4.2 on 2025-12-08 21:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MatchDeportivoAPP', '0002_actividad_alter_log_usuario_perfil_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Puntuación de 1 a 5 estrellas', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, help_text='Comentario opcional sobre la experiencia', max_length=500)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(help_text='Actividad en la que participaron', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='MatchDeportivoAPP.actividad')),
                ('evaluado', models.ForeignKey(help_text='Usuario que recibe la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('evaluador', models.ForeignKey(help_text='Usuario que realiza la valoración', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones_dadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoración',
                'verbose_name_plural': 'Valoraciones',
                'ordering': ['-fecha_creacion'],
                'unique_together': {('evaluador', 'evaluado', 'actividad')},
            },
        ),
    ]
