# Generated by Django 4.2 on 2025-12-10 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchDeportivoAPP', '0003_valoracion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='longitud',
        ),
    ]
