# Generated by Django 4.2 on 2025-12-10 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchDeportivoAPP', '0004_remove_actividad_latitud_remove_actividad_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='cerrada',
            field=models.BooleanField(default=False, help_text='Indica si la actividad ya finalizó y está cerrada'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se cerró la actividad', null=True),
        ),
    ]
