# Generated by Django 4.2 on 2025-12-10 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MatchDeportivoAPP', '0005_actividad_cerrada_actividad_fecha_cierre'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
